apiVersion: v1
kind: ConfigMap
metadata:
    name: porthole-config
    namespace: porthole
data:
    porthole-config.json: |-
        {
            "namespaces-to-skip": [
            ],
            "frontend-pattern-matching": [
                "frontend"
            ],
            "refresh-interval": 30,
            "portal-title": "porthole1"
        }