apiVersion: v1
kind: ConfigMap
metadata:
  name: openresty-server-config
  namespace: k8s-service-proxy
data:
  default.conf: |2-
    server {
        listen 7070;
        server_name _;
        location / {
            root /app/static;
            index index.html;
            try_files $uri $uri/ @fallback;
        }
        location /services.json {
            root /app/generated-output;
            try_files $uri =404;
        }
        location @fallback {
            root /app/generated-output;
            autoindex on;
            autoindex_exact_size off;
            autoindex_localtime on;
        }
        include /app/generated-output/locations.conf;
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-service-proxy
  namespace: k8s-service-proxy
  labels:
    app.kubernetes.io/name: k8s-service-proxy
    app.kubernetes.io/component: service-discovery
    app.kubernetes.io/version: "0.2.8"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: k8s-service-proxy
      app.kubernetes.io/component: service-discovery
  template:
    metadata:
      labels:
        app.kubernetes.io/name: k8s-service-proxy
        app.kubernetes.io/component: service-discovery
        app.kubernetes.io/version: "0.2.8"
      annotations:
        prometheus.io/scrape: "false"
    spec:
      serviceAccountName: k8s-service-proxy
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
      initContainers:
      - name: config-generator
        image: jgoodier/k8s-service-proxy:0.2.8
        env:
        - name: OUTPUT_DIR
          value: "/app/generated-output"
        - name: DEBUG
          value: "false"
        - name: SKIP_NAMESPACES
          value: "kube-system,kube-public,kube-node-lease"
        command: ["python", "-m", "porthole.porthole", "generate"]
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: app-generated-output
          mountPath: /app/generated-output
      containers:
      - name: openresty
        image: bitnami/openresty:latest
        ports:
        - name: http
          containerPort: 7070
          protocol: TCP
        volumeMounts:
          - name: app-generated-output
            mountPath: /app/generated-output
          - name: portal-static-files
            mountPath: /app/static
          - name: openresty-server-config
            mountPath: /opt/bitnami/openresty/nginx/conf/server_blocks
          - name: openresty-tmp
            mountPath: /opt/bitnami/openresty/nginx/tmp
      - name: k8s-service-proxy
        image: jgoodier/k8s-service-proxy:0.2.8
        imagePullPolicy: IfNotPresent
        env:
        - name: OUTPUT_DIR
          value: "/app/generated-output"
        - name: REFRESH_INTERVAL
          value: "300"
        - name: PORTAL_TITLE
          value: "Kubernetes Services Portal"
        - name: DEBUG
          value: "false"
        - name: SKIP_NAMESPACES
          value: "kube-system,kube-public,kube-node-lease"
        command: ["/app/scripts/startup-watch-serve.sh"]
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "100m"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: app-generated-output
          mountPath: /app/generated-output
        - name: portal-static-files
          mountPath: /app/static
      volumes:
      - name: app-generated-output
        emptyDir: {}
      - name: portal-static-files
        configMap:
          name: portal-static-files
      - name: openresty-server-config
        configMap:
          name: openresty-server-config
      - name: openresty-tmp
        emptyDir: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-service-proxy
  namespace: k8s-service-proxy
  labels:
    app.kubernetes.io/name: k8s-service-proxy
    app.kubernetes.io/component: service-discovery
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 7070
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: k8s-service-proxy
    app.kubernetes.io/component: service-discovery
