
apiVersion: apps/v1
kind: Deployment
metadata:
  name: porthole
  namespace: porthole
  labels:
    app.kubernetes.io/name: porthole
    app.kubernetes.io/component: kubernetes-service-proxy
    app.kubernetes.io/version: "0.2.21"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: porthole
      app.kubernetes.io/component: kubernetes-service-proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: porthole
        app.kubernetes.io/component: kubernetes-service-proxy
        app.kubernetes.io/version: "0.2.21"
    spec:
      serviceAccountName: porthole
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
      initContainers:
      - name: init-config-generator
        image: jgoodier/porthole:0.2.21
        env:
        - name: OUTPUT_DIR
          value: "/app/generated-output"
        - name: DEBUG
          value: "false"
        - name: SKIP_NAMESPACES
          value: "kube-system,kube-public,kube-node-lease"
        command: ["python", "-m", "porthole.porthole", "generate"]
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: app-generated-output
          mountPath: /app/generated-output
      containers:
      - name: openresty
        image: bitnami/openresty:latest
        ports:
        - name: http
          containerPort: 7070
          protocol: TCP
        volumeMounts:
          - name: app-generated-output
            mountPath: /app/generated-output
          - name: portal-static-files
            mountPath: /app/static
          - name: openresty-server-config
            mountPath: /opt/bitnami/openresty/nginx/conf/server_blocks
          - name: openresty-tmp
            mountPath: /opt/bitnami/openresty/nginx/tmp
      - name: porthole
        image: jgoodier/porthole:0.2.21
        imagePullPolicy: IfNotPresent
        env:
        - name: OUTPUT_DIR
          value: "/app/generated-output"
        - name: REFRESH_INTERVAL
          value: "300"
        - name: PORTAL_TITLE
          value: "Kubernetes Services Portal"
        - name: DEBUG
          value: "false"
        - name: SKIP_NAMESPACES
          value: "kube-system,kube-public,kube-node-lease"
        command: ["/app/scripts/startup-watch.sh"]
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "100m"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: app-generated-output
          mountPath: /app/generated-output
        - name: portal-static-files
          mountPath: /app/static
        - name: porthole-config
          mountPath: /app/config
      volumes:
      - name: app-generated-output
        emptyDir: {}
      - name: portal-static-files
        configMap:
          name: portal-static-files
      - name: openresty-server-config
        configMap:
          name: openresty-server-config
      - name: openresty-tmp
        emptyDir: {}
      - name: porthole-config
        configMap:
          name: porthole-config
      restartPolicy: Always
      terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: porthole
  namespace: porthole
  labels:
    app.kubernetes.io/name: porthole
    app.kubernetes.io/component: kubernetes-service-proxy
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 7070
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: porthole
    app.kubernetes.io/component: kubernetes-service-proxy
