---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: porthole
  namespace: porthole
  labels:
    app.kubernetes.io/name: porthole
    app.kubernetes.io/component: kubernetes-service-proxy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: porthole
  labels:
    app.kubernetes.io/name: porthole
    app.kubernetes.io/component: kubernetes-service-proxy
rules:
# Services discovery
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
# Endpoints discovery (k8s 1.32 and earlier)
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch"]
# EndpointSlices discovery (k8s 1.33+)
- apiGroups: ["discovery.k8s.io"]
  resources: ["endpointslices"]
  verbs: ["get", "list", "watch"]
# Namespaces discovery
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]
# Nodes for cluster info
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
# API resources for cluster info
- apiGroups: [""]
  resources: [""]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: porthole
  labels:
    app.kubernetes.io/name: porthole
    app.kubernetes.io/component: kubernetes-service-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: porthole
subjects:
- kind: ServiceAccount
  name: porthole
  namespace: porthole