apiVersion: v1
kind: Service
metadata:
  name: porthole
  namespace: porthole
  labels:
    app.kubernetes.io/name: porthole
    app.kubernetes.io/component: kubernetes-service-proxy
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 7070
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: porthole
    app.kubernetes.io/component: kubernetes-service-proxy
