version: "3.8"

services:
  frontend:
    image: bitnami/openresty:latest
    ports:
    - "7070:7070"
    volumes:
    - ../generated-output:/app/generated-output:Z
    restart: unless-stopped
    network_mode: host
  backend:
    image: porthole-dev:latest
    env:
    - KUBECONFIG=/app/.kubeconfig
    ports: [] # If you don’t need to expose any ports
    volumes:
    - ../generated-output:/app/generated-output:Z
    - ../.kubeconfig:/app/.kubeconfig:ro
    environment:
    - KUBECONFIG=/app/.kubeconfig
    restart: unless-stopped
    network_mode: host
volumes:
  generated-output:
    driver: local
